# Generated by Django 3.0 on 2020-01-15 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POST', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
    ]
