# Generated by Django 3.0 on 2020-01-15 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POST', '0002_auto_20200115_1536'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Posts',
        ),
    ]
