# Generated by Django 3.0 on 2020-01-15 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POST', '0003_auto_20200115_1540'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'verbose_name_plural': 'Posts'},
        ),
    ]
