# Generated by Django 3.0 on 2020-01-15 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POST', '0004_auto_20200115_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='tittle',
            new_name='title',
        ),
    ]
